//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System;
using System.Linq;
using System.Collections.Generic;
using Woozle.Model;
using Woozle.Model.SessionHandling;
using Woozle.Persistence;
using Woozle.Persistence.Ef;
using Woozle.Persistence.Ef.Repository;
using Woozle.Demo.Model;

namespace Woozle.Demo.Persistence
{
    public interface IWoozleDemoUnitOfWork : IEfUnitOfWork 
    {
    }
}
